# https://taskfile.dev

version: "3"

dotenv:
  - .env

vars:
  PROTOBUF_DIR: _deps/grpc-build/third_party/protobuf

tasks:
  proto:
    cmds:
      - platforms: [windows]
        cmd: >
          $BUILD_DIR/{{.PROTOBUF_DIR}}/protoc.exe
          -I proto
          --cpp_out=proto/generated/raftpp
          raftpp.proto
  vs:
    platforms: [windows]
    cmds:
      - cmake -S . -B vs -G "Visual Studio 17 2022"

  fmt:
    platforms: [linux]
    cmds:
      - >
        clang-format --style=file -i
        $(git ls-files | grep '.cc$\|.h$\|.hpp$' | grep -v 'sqlite3ext\.\|sqlite3\.\|\.pb\.\|generated')

  cmake:
    cmds:
      - cmake --preset=dev

  build-test:
    deps:
      - cmake
    cmds:
      - cmake --build build --target raftpp-tests

  list-tests:
    deps:
      - build-test
    cmds:
      - ./build/tests/raftpp-tests --gtest_list_tests

  test:
    deps:
      - build-test
    cmds:
      - ./build/tests/raftpp-tests
