#pragma once

#include <cstdint>
#include <unordered_map>
#include <vector>

#include "interface.h"
#include "raftpp/error.h"
#include "raftpp/memory_storage.h"
#include "raftpp/raft_config.h"
#include "raftpp/raftpp.pb.h"

namespace raftpp {

/// A connection from one node to another.
///
/// Used in by `Network` for determining drop rates on messages.
struct Connection {
    uint64_t from;
    uint64_t to;

    bool operator==(const Connection& other) const { return from == other.from && to == other.to; }
};

/// A simulated network for testing.
///
/// You can use this to create a test network of Raft nodes.
///
/// *Please note:* no actual network calls are made.
class Network {
  public:
    Network() = default;

    /// Create a network with specified number of peers.
    /// Nodes will receive their ID based on their index, starting with 1.
    static Network CreateWithConfig(size_t num_peers, const Config& config);

    /// Get a peer by ID.
    [[nodiscard]] Interface* GetPeer(uint64_t id);
    [[nodiscard]] const Interface* GetPeer(uint64_t id) const;

    /// Get storage by ID.
    [[nodiscard]] MemoryStorage* GetStorage(uint64_t id);
    [[nodiscard]] const MemoryStorage* GetStorage(uint64_t id) const;

    /// Ignore a given `MessageType`.
    void IgnoreMessageType(MessageType type);

    /// Filter out messages that should be dropped according to rules set.
    std::vector<Message> Filter(const std::vector<Message>& msgs);

    /// Read out all messages generated by peers in the `Network`.
    ///
    /// Note: messages are not filtered by any configured filters.
    std::vector<Message> ReadMessages();

    /// Instruct cluster to `step` through given messages.
    ///
    /// NOTE: given `msgs` won't be filtered by its filters.
    void Send(std::vector<Message> msgs);

    /// Filter `msgs` and then instruct cluster to `step` through given messages.
    void FilterAndSend(std::vector<Message> msgs);

    /// Dispatch given messages to appropriate peers.
    ///
    /// Unlike `send` this does not gather and send any responses.
    Result<void> Dispatch(const std::vector<Message>& messages);

    /// Ignore messages from `from` to `to` at `percentage` percent chance.
    ///
    /// `percentage` set to `1.0` is a 100% chance, `0.0` is a 0% chance.
    void Drop(uint64_t from, uint64_t to, double percentage);

    /// Cut communication between two given nodes.
    void Cut(uint64_t one, uint64_t other);

    /// Isolate a given node to and from all other nodes in the cluster.
    void Isolate(uint64_t id);

    /// Recover cluster conditions applied with `Drop` and `IgnoreMessageType`.
    void Recover();

    /// Get number of peers in the network.
    [[nodiscard]] size_t Size() const { return peers_.size(); }

    /// Get all peers
    [[nodiscard]] const std::unordered_map<uint64_t, Interface>& Peers() const { return peers_; }

  private:
    explicit Network(
        std::unordered_map<uint64_t, Interface> peers,
        std::unordered_map<uint64_t, MemoryStorage*> storage
    );

    std::unordered_map<uint64_t, Interface> peers_;
    std::unordered_map<uint64_t, MemoryStorage*> storage_;
    std::unordered_map<uint64_t, bool> ignore_message_types_;
    std::unordered_map<Connection, double> drop_rates_;
};

// Simple hash function for Connection struct
inline uint64_t hash_connection(const Connection& c) {
    return (c.from << 32) | c.to;
}

}  // namespace raftpp

// Specialize std::hash for Connection in raftpp namespace
namespace std {

template <>
struct hash<raftpp::Connection> {
    std::size_t operator()(const raftpp::Connection& c) const noexcept {
        return std::hash<uint64_t>{}(raftpp::hash_connection(c));
    }
};

}  // namespace std
